services:
    client:
        build:
            context: ./Client
        ports:
            - "80:80"
        env_file:
            - ./Client/.env
        networks:
            - cluetact-network

    server:
        build:
            context: ./Server
        ports:
            - "8000:8000"
        env_file:
            - ./Server/.env
        networks:
            - cluetact-network

networks:
    cluetact-network:
        driver: bridge
