services:
  app:
    build: .
    container_name: game_server
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongo
      - redis
    command: ["npm", "start"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"