const GAME_STAGES = Object.freeze({
    PRE_ROUND: "PRE_ROUND",
    KEEPER_CHOOSING_WORD: "KEEPER_CHOOSING_WORD",
    CLUE_SUBMISSION_POST_CLUETACT: "CLUE_SUBMISSION_POST_CLUETACT",
    CLUE_SUBMISSION: "CLUE_SUBMISSION",
    RACE: "RACE",
    MID_ROUND: "MID_ROUND", // ?
    END: "END",
});

module.exports = GAME_STAGES;
